import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <div className="bg-gray-50">
          <div className="fixed top-0 left-0 w-full z-50 h-[30px]">
            <Navbar />
          </div>
          <div className="mt-[40px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
